# Generated by Django 5.2.7 on 2025-12-14 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExistenciaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('medida', models.CharField(choices=[('Unidades', 'Unidades'), ('Metros', 'Metros')], max_length=20)),
                ('existencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_dolar', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Existencia de Insumo',
                'verbose_name_plural': 'Existencias de Insumos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CompraInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(choices=[('Bs', 'Bolívares'), ('$', 'Dólares')], max_length=2)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto en la moneda seleccionada', max_digits=15)),
                ('aplicar_iva', models.BooleanField(default=False, verbose_name='Aplicar IVA (16%)')),
                ('monto_bs', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True)),
                ('monto_usd', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True)),
                ('monto_iva_bs', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True)),
                ('monto_iva_usd', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True)),
                ('monto_total_bs', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True)),
                ('monto_total_usd', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='Inventario.existenciainsumo')),
            ],
            options={
                'verbose_name': 'Compra de Insumo',
                'verbose_name_plural': 'Compras de Insumos',
                'ordering': ['-fecha_compra'],
            },
        ),
    ]
