# Generated by Django 5.2.7 on 2025-12-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='existenciainsumo',
            name='existencia_minima',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Existencia mínima requerida', max_digits=10),
        ),
    ]
