# Generated by Django 5.2.7 on 2025-12-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_existenciainsumo_existencia_minima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existenciainsumo',
            name='costo_dolar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo unitario en USD (se calcula automáticamente al registrar compras)', max_digits=10, null=True),
        ),
    ]
