# Generated by Django 5.2.7 on 2025-12-14 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_alter_existenciainsumo_costo_dolar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_uso', models.DateField(verbose_name='Fecha de Uso')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción del Uso')),
                ('costo_total_usd', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Costo Total (USD)')),
            ],
            options={
                'verbose_name': 'Uso de Insumo',
                'verbose_name_plural': 'Usos de Insumos',
                'ordering': ['-fecha_uso'],
            },
        ),
        migrations.CreateModel(
            name='DetalleUsoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Utilizada')),
                ('costo_unitario_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario (USD)')),
                ('costo_total_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Costo Total (USD)')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='Inventario.existenciainsumo')),
                ('uso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Inventario.usoinsumo')),
            ],
            options={
                'verbose_name': 'Detalle de Uso',
                'verbose_name_plural': 'Detalles de Uso',
            },
        ),
    ]
