# Generated by Django 5.2.7 on 2025-12-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_existenciainsumo_categoria_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprainsumo',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Factura'),
        ),
    ]
