# Generated by Django 5.2.7 on 2025-12-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_comprainsumo_numero_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprainsumo',
            name='anulada',
            field=models.BooleanField(default=False, help_text='Indica si esta compra ha sido anulada', verbose_name='Anulada'),
        ),
        migrations.AddField(
            model_name='comprainsumo',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Anulación'),
        ),
    ]
