# Generated by Django 5.2.7 on 2025-12-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0008_comprainsumo_anulada_comprainsumo_fecha_anulacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventario', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número de Inventario')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de Adquisición')),
                ('tipo_activo', models.CharField(choices=[('Mobiliario', 'Mobiliario'), ('Equipo de Oficina', 'Equipo de Oficina'), ('Vehículo', 'Vehículo'), ('Maquinaria', 'Maquinaria'), ('Tecnología', 'Tecnología'), ('Otros', 'Otros')], max_length=50, verbose_name='Tipo de Activo')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Serial')),
                ('moneda', models.CharField(choices=[('Bs', 'Bolívares'), ('$', 'Dólares')], max_length=2, verbose_name='Moneda')),
                ('valor_adquisicion', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Adquisición')),
                ('valor_dolares', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Valor en Dólares')),
                ('depreciacion_anual', models.DecimalField(decimal_places=2, help_text='Porcentaje de depreciación anual (ej: 20.00 para 20%)', max_digits=5, verbose_name='Depreciación Anual (%)')),
                ('depreciacion_acumulada', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Depreciación Acumulada (USD)')),
                ('valor_actual', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Valor Actual (USD)')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('En Mantenimiento', 'En Mantenimiento'), ('Dado de Baja', 'Dado de Baja'), ('Vendido', 'Vendido')], default='Activo', max_length=20, verbose_name='Estado')),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación')),
                ('responsable', models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsable')),
                ('fecha_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Última Fecha de Mantenimiento')),
                ('descripcion_mantenimiento', models.TextField(blank=True, null=True, verbose_name='Descripción del Mantenimiento')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='activos_fijos/', verbose_name='Foto del Activo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
                'ordering': ['-fecha_adquisicion', 'numero_inventario'],
            },
        ),
    ]
