# Generated by Django 5.2.7 on 2025-12-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0009_activofijo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activofijo',
            name='tipo_activo',
            field=models.CharField(choices=[('Maquinaria', 'Maquinaria'), ('Herramienta', 'Herramienta'), ('Mobiliario', 'Mobiliario'), ('Equipo de Oficina', 'Equipo de Oficina'), ('Vehículo', 'Vehículo'), ('Tecnología', 'Tecnología'), ('Otros', 'Otros')], max_length=50, verbose_name='Tipo de Activo'),
        ),
    ]
