# Generated by Django 5.2.7 on 2025-12-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0010_alter_activofijo_tipo_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activofijo',
            name='garantia_meses',
            field=models.IntegerField(default=0, help_text='Duración de la garantía en meses desde la fecha de adquisición', verbose_name='Garantía (meses)'),
        ),
    ]
