# Generated by Django 5.2.7 on 2025-12-20 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0011_activofijo_garantia_meses'),
        ('ProveedoresApp', '0002_proveedores_rif'),
    ]

    operations = [
        migrations.AddField(
            model_name='activofijo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_fijos', to='ProveedoresApp.proveedores', verbose_name='Proveedor'),
        ),
    ]
