# Generated by Django 5.2.7 on 2025-12-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0012_activofijo_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='activofijo',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción Corta'),
        ),
    ]
