# Generated by Django 5.2.7 on 2025-12-27 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClientesApp', '0002_clientes_busto_clientes_cintura_clientes_copa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vestido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=200, verbose_name='Nombre/Modelo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('talla', models.CharField(max_length=20, verbose_name='Talla')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('tipo_moneda', models.CharField(choices=[('Bs', 'Bolívares'), ('$', 'Dólares')], max_length=2, verbose_name='Tipo de Moneda')),
                ('precio_alquiler', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Alquiler')),
                ('deposito', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Depósito')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Compra')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Alquilado', 'Alquilado'), ('Tintorería', 'Tintorería'), ('Arreglo', 'Arreglo'), ('Dañado', 'Dañado')], default='Disponible', max_length=20, verbose_name='Estado')),
                ('foto1', models.ImageField(upload_to='vestidos/', verbose_name='Foto 1')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='vestidos/', verbose_name='Foto 2')),
                ('accesorios', models.TextField(blank=True, null=True, verbose_name='Accesorios Incluidos')),
                ('fecha_tintoreria', models.DateField(blank=True, null=True, verbose_name='Fecha de Envío a Tintorería')),
                ('fecha_entrega_tintoreria', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega de Tintorería')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vestido',
                'verbose_name_plural': 'Vestidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contrato', models.DateField(verbose_name='Fecha de Contrato')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_devolucion_prevista', models.DateField(verbose_name='Fecha de Devolución Prevista')),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución Real')),
                ('anticipo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Anticipo')),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Final')),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Parcial', 'Parcial')], default='Pendiente', max_length=20, verbose_name='Estado de Pago')),
                ('estado_alquiler', models.CharField(choices=[('Activo', 'Activo'), ('Completado', 'Completado'), ('Retrasado', 'Retrasado'), ('Cancelado', 'Cancelado')], default='Activo', max_length=20, verbose_name='Estado del Alquiler')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alquileres', to='ClientesApp.clientes', verbose_name='Cliente')),
                ('vestido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alquileres', to='Alquiler.vestido', verbose_name='Vestido')),
            ],
            options={
                'verbose_name': 'Alquiler',
                'verbose_name_plural': 'Alquileres',
                'ordering': ['-fecha_contrato'],
            },
        ),
    ]
