# Generated by Django 5.2.7 on 2025-12-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquiler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vestido',
            name='deposito',
        ),
        migrations.RemoveField(
            model_name='vestido',
            name='tipo_moneda',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='deposito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Depósito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alquiler',
            name='tipo_moneda',
            field=models.CharField(choices=[('Bs', 'Bolívares'), ('$', 'Dólares')], default='$', max_length=2, verbose_name='Tipo de Moneda'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='total_usd',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total en USD'),
        ),
    ]
