# Generated by Django 5.2.7 on 2025-12-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquiler', '0002_remove_vestido_deposito_remove_vestido_tipo_moneda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='estado_alquiler',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Entregado', 'Entregado'), ('Devuelto', 'Devuelto'), ('Completado', 'Completado'), ('Retrasado', 'Retrasado'), ('Cancelado', 'Cancelado')], default='Activo', max_length=20, verbose_name='Estado del Alquiler'),
        ),
        migrations.AlterField(
            model_name='vestido',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Alquilado', 'Alquilado'), ('Tintorería', 'Tintorería'), ('Arreglo', 'Arreglo'), ('Dañado', 'Dañado'), ('Vendido', 'Vendido'), ('Baja', 'Baja')], default='Disponible', max_length=20, verbose_name='Estado'),
        ),
    ]
