# Generated by Django 5.2.7 on 2025-12-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquiler', '0003_alter_alquiler_estado_alquiler_alter_vestido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='estado_alquiler',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Entregado', 'Entregado'), ('Devuelto', 'Devuelto'), ('Retrasado', 'Retrasado'), ('Cancelado', 'Cancelado')], default='Activo', max_length=20, verbose_name='Estado del Alquiler'),
        ),
    ]
