# Generated by Django 5.2.7 on 2025-12-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquiler', '0004_alter_alquiler_estado_alquiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='pago_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pago Total Recibido'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='pago_total_usd',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Pago Total en USD'),
        ),
        migrations.AddField(
            model_name='vestido',
            name='deposito_garantia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Depósito de Garantía'),
        ),
    ]
