# Generated by Django 5.2.7 on 2025-12-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquiler', '0005_alquiler_pago_total_alquiler_pago_total_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='pago_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pago Final/Liquidación'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='pago_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Pago Total Recibido'),
        ),
    ]
