# Generated by Django 5.2.7 on 2025-12-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquiler', '0006_alquiler_pago_final_alter_alquiler_pago_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestido',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='vestidos/', verbose_name='Foto 3'),
        ),
        migrations.AddField(
            model_name='vestido',
            name='foto4',
            field=models.ImageField(blank=True, null=True, upload_to='vestidos/', verbose_name='Foto 4'),
        ),
    ]
