# Generated by Django 5.2.7 on 2025-11-30 21:49

from django.db import migrations, models
from datetime import time


def set_default_hora(apps, schema_editor):
    """Set a default time for records with NULL hora"""
    Cita = apps.get_model('citas', 'Cita')
    # Update records with NULL hora to have a default time
    Cita.objects.filter(hora__isnull=True).update(hora=time(0, 0))


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_cita_copa_cita_tiras'),
    ]

    operations = [
        # First, set default values for NULL hora fields
        migrations.RunPython(set_default_hora, reverse_code=migrations.RunPython.noop),
        # Then alter the fields to allow NULL
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
