# Generated by Django 5.2.7 on 2025-12-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Depósito', 'Depósito'), ('Transferencia', 'Transferencia'), ('Pago Móvil', 'Pago Móvil'), ('Otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='tipo_movimiento',
            field=models.CharField(blank=True, choices=[('Venta', 'Venta'), ('Compra de Insumos', 'Compra de Insumos'), ('Nómina', 'Nómina'), ('Alquiler', 'Alquiler'), ('Otros', 'Otros')], max_length=20, null=True),
        ),
    ]
