# Generated by Django 5.2.7 on 2025-12-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0002_movimientocaja_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='numero_factura',
            field=models.CharField(blank=True, help_text='Número de factura asociado (para compras de insumos)', max_length=50, null=True, verbose_name='Número de Factura'),
        ),
    ]
