# Generated by Django 5.2.7 on 2025-12-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0003_movimientocaja_numero_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha a partir de la cual aplica este porcentaje de IVA', unique=True, verbose_name='Fecha de Inicio')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Ejemplo: 16.00 para 16%', max_digits=5, verbose_name='Porcentaje de IVA')),
                ('activo', models.BooleanField(default=True, help_text='Solo las configuraciones activas se usan en los cálculos', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Configuración de IVA',
                'verbose_name_plural': 'Configuraciones de IVA',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
