# Generated by Django 5.2.7 on 2025-12-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0004_configuracioniva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egresos', 'Egresos')], max_length=10),
        ),
    ]
