# Generated by Django 5.2.7 on 2025-12-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='busto',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Busto'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cintura',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cintura'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='copa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Copa'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='historial',
            field=models.TextField(blank=True, null=True, verbose_name='Historial de Alquileres'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='largo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Largo'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='otras',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otras Medidas'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='tiras',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tiras'),
        ),
    ]
