# Generated by Django 5.2.7 on 2025-12-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueApp', '0003_alter_catalogo_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Foto 2'),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Foto 3'),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='foto4',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Foto 4'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='imagen_modelo',
            field=models.ImageField(null=True, upload_to='imagenes', verbose_name='Foto 1'),
        ),
    ]
